# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.10.0 on Fri May  3 19:39:34 2024.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for LEDBlinkService
class ILEDBlinkService(object):
    SERVICE_ID = 1
    LED_ON_ID = 1
    LED_OFF_ID = 2

    def led_on(self, led):
        raise NotImplementedError()

    def led_off(self, led):
        raise NotImplementedError()


