/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.10.0 on Fri May  3 19:39:22 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_blink_led_server_h_)
#define _blink_led_server_h_

#ifdef __cplusplus
#include "erpc_server.hpp"
#include "erpc_codec.hpp"
extern "C"
{
#include "blink_led.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


/*!
 * @brief Service subclass for LEDBlinkService.
 */
class LEDBlinkService_service : public erpc::Service
{
public:
    LEDBlinkService_service() : Service(kLEDBlinkService_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for led_on of LEDBlinkService interface. */
    erpc_status_t led_on_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for led_off of LEDBlinkService interface. */
    erpc_status_t led_off_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "blink_led.h"
#endif // __cplusplus

typedef void * erpc_service_t;

/*! @brief Return LEDBlinkService_service service object. */
erpc_service_t create_LEDBlinkService_service(void);

/*! @brief Destroy LEDBlinkService_service service object. */
void destroy_LEDBlinkService_service(erpc_service_t service);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _blink_led_server_h_
